### ISSUE TITLE
Count in Case of Multiple categories

### ISSUE THREAD

**Issue by jaideep11061982** [Verg-Avesta/CounTR#15]
@Verg-Avesta  so far your model working good on our images. 
I have this q 
1) If suppose there are multiple categories of objects present in counting area  say Cat A-4, Cat B-5 , Cat C-10
What is going to be count returned by the model, can it provide Category wise count  as shown above or  total count i.e 19 in this case.

2) For better counting results do I have to give atleast 1 BBX from each cat as assistance ?

**Comment by Verg-Avesta** [comment]
1. The counting results depend on how different these categories are and what exemplars you provide. There are no deterministic results about what the model will count when the object categories are similar.

2. You don't have to do this this because the model itself can generalize to a certain degree, but providing more representative exemplars will very likely to improve the performance.
